import { useState, useMemo, useRef, useEffect } from "react";

// ---- Data -----------------------------------------------------------------
// Country centroids (approx lat/lng). This drives the REAL distance/direction
// math. In production this comes from Natural Earth; hardcoded here for the
// prototype.
const COUNTRIES = [
  { name: "Switzerland", lat: 46.8, lng: 8.2 },
  { name: "France", lat: 46.6, lng: 2.2 },
  { name: "Germany", lat: 51.1, lng: 10.4 },
  { name: "Italy", lat: 42.8, lng: 12.6 },
  { name: "Austria", lat: 47.6, lng: 14.1 },
  { name: "Liechtenstein", lat: 47.2, lng: 9.5 },
  { name: "Nepal", lat: 28.4, lng: 84.1 },
  { name: "India", lat: 22.0, lng: 79.0 },
  { name: "China", lat: 35.9, lng: 104.2 },
  { name: "Paraguay", lat: -23.4, lng: -58.4 },
  { name: "Bolivia", lat: -16.3, lng: -63.6 },
  { name: "Brazil", lat: -10.8, lng: -53.1 },
  { name: "Argentina", lat: -38.4, lng: -63.6 },
  { name: "Czechia", lat: 49.8, lng: 15.5 },
  { name: "Slovakia", lat: 48.7, lng: 19.7 },
  { name: "Hungary", lat: 47.2, lng: 19.4 },
  { name: "Slovenia", lat: 46.1, lng: 14.8 },
  { name: "Belgium", lat: 50.6, lng: 4.6 },
  { name: "Netherlands", lat: 52.1, lng: 5.3 },
  { name: "Luxembourg", lat: 49.8, lng: 6.1 },
  { name: "Laos", lat: 18.2, lng: 103.9 },
  { name: "Thailand", lat: 15.1, lng: 101.0 },
  { name: "Vietnam", lat: 16.2, lng: 106.3 },
  { name: "Cambodia", lat: 12.6, lng: 104.9 },
  { name: "Myanmar", lat: 21.9, lng: 95.9 },
  { name: "Ecuador", lat: -1.4, lng: -78.2 },
  { name: "Colombia", lat: 4.6, lng: -74.3 },
  { name: "Peru", lat: -9.2, lng: -75.0 },
  { name: "Spain", lat: 40.2, lng: -3.6 },
  { name: "Portugal", lat: 39.5, lng: -8.0 },
  { name: "Poland", lat: 51.9, lng: 19.1 },
  { name: "Ukraine", lat: 48.4, lng: 31.2 },
  { name: "Romania", lat: 45.9, lng: 24.9 },
  { name: "Greece", lat: 39.1, lng: 21.8 },
  { name: "Turkey", lat: 39.0, lng: 35.2 },
  { name: "Russia", lat: 61.5, lng: 105.3 },
  { name: "Japan", lat: 36.2, lng: 138.3 },
  { name: "South Korea", lat: 36.5, lng: 127.8 },
  { name: "Indonesia", lat: -2.5, lng: 118.0 },
  { name: "Mexico", lat: 23.6, lng: -102.5 },
  { name: "United States", lat: 39.8, lng: -98.6 },
  { name: "Canada", lat: 56.1, lng: -106.3 },
  { name: "Chile", lat: -35.7, lng: -71.5 },
  { name: "Egypt", lat: 26.8, lng: 30.8 },
  { name: "Kenya", lat: 0.0, lng: 37.9 },
  { name: "Nigeria", lat: 9.1, lng: 8.7 },
  { name: "South Africa", lat: -30.6, lng: 22.9 },
  { name: "Morocco", lat: 31.8, lng: -7.1 },
  { name: "Iran", lat: 32.4, lng: 53.7 },
  { name: "Iraq", lat: 33.2, lng: 43.7 },
  { name: "Saudi Arabia", lat: 23.9, lng: 45.1 },
  { name: "Pakistan", lat: 30.4, lng: 69.3 },
  { name: "Bangladesh", lat: 23.7, lng: 90.4 },
  { name: "Kazakhstan", lat: 48.0, lng: 66.9 },
  { name: "Mongolia", lat: 46.9, lng: 103.8 },
  { name: "Norway", lat: 60.5, lng: 8.5 },
  { name: "Sweden", lat: 60.1, lng: 18.6 },
  { name: "Finland", lat: 61.9, lng: 25.7 },
  { name: "Denmark", lat: 56.3, lng: 9.5 },
  { name: "United Kingdom", lat: 55.4, lng: -3.4 },
  { name: "Ireland", lat: 53.4, lng: -8.2 },
];

const BY_NAME = Object.fromEntries(COUNTRIES.map((c) => [c.name, c]));

// Each puzzle: the removed country + the neighbors whose territory would
// absorb it. In production this list (and the map art) is generated by the
// geometry pipeline.
const PUZZLES = [
  { target: "Switzerland", neighbors: ["France", "Germany", "Italy", "Austria", "Liechtenstein"] },
  { target: "Nepal", neighbors: ["India", "China"] },
  { target: "Paraguay", neighbors: ["Bolivia", "Brazil", "Argentina"] },
  { target: "Austria", neighbors: ["Germany", "Czechia", "Slovakia", "Hungary", "Slovenia", "Italy", "Switzerland", "Liechtenstein"] },
  { target: "Belgium", neighbors: ["France", "Netherlands", "Germany", "Luxembourg"] },
  { target: "Laos", neighbors: ["Thailand", "Vietnam", "Cambodia", "China", "Myanmar"] },
  { target: "Ecuador", neighbors: ["Colombia", "Peru"] },
];

const MAX_GUESSES = 6;
const MAX_DIST = 20000; // km, for proximity %

// ---- Geo math -------------------------------------------------------------
const toRad = (d) => (d * Math.PI) / 180;
const toDeg = (r) => (r * 180) / Math.PI;

function haversine(a, b) {
  const R = 6371;
  const dLat = toRad(b.lat - a.lat);
  const dLng = toRad(b.lng - a.lng);
  const lat1 = toRad(a.lat);
  const lat2 = toRad(b.lat);
  const h =
    Math.sin(dLat / 2) ** 2 +
    Math.cos(lat1) * Math.cos(lat2) * Math.sin(dLng / 2) ** 2;
  return 2 * R * Math.asin(Math.sqrt(h));
}

// bearing from a -> b, degrees clockwise from North
function bearing(a, b) {
  const lat1 = toRad(a.lat);
  const lat2 = toRad(b.lat);
  const dLng = toRad(b.lng - a.lng);
  const y = Math.sin(dLng) * Math.cos(lat2);
  const x =
    Math.cos(lat1) * Math.sin(lat2) -
    Math.sin(lat1) * Math.cos(lat2) * Math.cos(dLng);
  return (toDeg(Math.atan2(y, x)) + 360) % 360;
}

const ARROWS = ["⬆️", "↗️", "➡️", "↘️", "⬇️", "↙️", "⬅️", "↖️"];
function arrowEmoji(bng) {
  return ARROWS[Math.round(bng / 45) % 8];
}

function proximityPct(distKm) {
  return Math.max(0, Math.round((1 - distKm / MAX_DIST) * 100));
}

// ---- Component ------------------------------------------------------------
export default function MissingCountryGame() {
  const [puzzleIdx, setPuzzleIdx] = useState(
    () => Math.floor(Date.now() / 8.64e7) % PUZZLES.length
  );
  const puzzle = PUZZLES[puzzleIdx];
  const target = BY_NAME[puzzle.target];

  const [guesses, setGuesses] = useState([]); // {name, dist, bng, pct}
  const [input, setInput] = useState("");
  const [showList, setShowList] = useState(false);
  const [revealHint, setRevealHint] = useState(false);
  const [copied, setCopied] = useState(false);
  const inputRef = useRef(null);

  const won = guesses.some((g) => g.name === puzzle.target);
  const done = won || guesses.length >= MAX_GUESSES;

  // reset transient state on puzzle change
  useEffect(() => {
    setGuesses([]);
    setInput("");
    setRevealHint(false);
    setCopied(false);
  }, [puzzleIdx]);

  const suggestions = useMemo(() => {
    if (!input.trim()) return [];
    const q = input.toLowerCase();
    const used = new Set(guesses.map((g) => g.name));
    return COUNTRIES.filter(
      (c) => c.name.toLowerCase().includes(q) && !used.has(c.name)
    ).slice(0, 6);
  }, [input, guesses]);

  function submitGuess(name) {
    if (done) return;
    const g = BY_NAME[name];
    if (!g) return;
    const dist = haversine(g, target);
    const bng = bearing(g, target);
    const entry = {
      name,
      dist: Math.round(dist),
      bng,
      pct: name === puzzle.target ? 100 : proximityPct(dist),
    };
    setGuesses((prev) => [...prev, entry]);
    setInput("");
    setShowList(false);
  }

  function shareText() {
    const header = `Missing Country #${puzzleIdx + 1} ${
      won ? guesses.length : "X"
    }/${MAX_GUESSES}`;
    const rows = guesses.map((g) => {
      if (g.name === puzzle.target) return "🟩🟩🟩🟩🟩🎯";
      const fill = Math.round(g.pct / 20);
      const squares =
        "🟩".repeat(fill) + "⬜".repeat(5 - fill);
      return squares + arrowEmoji(g.bng);
    });
    return [header, ...rows, "🌍 play at your-domain.com"].join("\n");
  }

  function copyShare() {
    const text = shareText();
    if (navigator.clipboard?.writeText) {
      navigator.clipboard.writeText(text).then(() => {
        setCopied(true);
        setTimeout(() => setCopied(false), 1600);
      });
    }
  }

  const remaining = MAX_GUESSES - guesses.length;

  return (
    <div className="min-h-screen bg-slate-950 text-slate-100 flex flex-col items-center py-8 px-4 font-sans">
      <div className="w-full max-w-md">
        {/* Header */}
        <div className="flex items-baseline justify-between mb-1">
          <h1 className="text-2xl font-bold tracking-tight">
            Missing Country
          </h1>
          <span className="text-xs text-slate-500">prototype</span>
        </div>
        <p className="text-sm text-slate-400 mb-5">
          One country was erased and swallowed by its neighbors. Which one is
          gone?
        </p>

        {/* Map placeholder */}
        <div className="relative rounded-2xl border border-slate-800 bg-gradient-to-br from-slate-900 to-slate-800/40 h-56 mb-2 overflow-hidden">
          <div className="absolute inset-0 flex flex-col items-center justify-center gap-2">
            <div className="relative">
              <div className="w-24 h-24 rounded-full bg-emerald-500/10 animate-pulse" />
              <div className="absolute inset-0 flex items-center justify-center text-5xl font-bold text-emerald-400/80">
                ?
              </div>
            </div>
            <p className="text-[11px] text-slate-500 text-center max-w-[80%] leading-snug">
              Pipeline-generated region art goes here — neighbors extended over
              the erased country. Placeholder for the prototype.
            </p>
          </div>
        </div>

        {/* Neighbor hint */}
        <div className="mb-5">
          <button
            onClick={() => setRevealHint((v) => !v)}
            className="text-xs text-slate-400 hover:text-slate-200 underline underline-offset-2"
          >
            {revealHint ? "Hide" : "Show"} neighbor hint ({puzzle.neighbors.length})
          </button>
          {revealHint && (
            <div className="mt-2 flex flex-wrap gap-1.5">
              {puzzle.neighbors.map((n) => (
                <span
                  key={n}
                  className="text-xs px-2 py-1 rounded-md bg-slate-800 text-slate-300"
                >
                  {n}
                </span>
              ))}
            </div>
          )}
        </div>

        {/* Guess input */}
        {!done && (
          <div className="relative mb-4">
            <div className="flex gap-2">
              <input
                ref={inputRef}
                value={input}
                onChange={(e) => {
                  setInput(e.target.value);
                  setShowList(true);
                }}
                onFocus={() => setShowList(true)}
                onKeyDown={(e) => {
                  if (e.key === "Enter" && suggestions[0])
                    submitGuess(suggestions[0].name);
                }}
                placeholder={`Guess a country (${remaining} left)`}
                className="flex-1 bg-slate-900 border border-slate-700 rounded-lg px-3 py-2.5 text-sm outline-none focus:border-emerald-500"
              />
              <button
                onClick={() =>
                  suggestions[0] && submitGuess(suggestions[0].name)
                }
                disabled={!suggestions[0]}
                className="px-4 rounded-lg bg-emerald-600 hover:bg-emerald-500 disabled:opacity-40 disabled:hover:bg-emerald-600 text-sm font-medium transition"
              >
                Guess
              </button>
            </div>
            {showList && suggestions.length > 0 && (
              <div className="absolute z-10 mt-1 w-full bg-slate-900 border border-slate-700 rounded-lg overflow-hidden shadow-xl">
                {suggestions.map((s) => (
                  <button
                    key={s.name}
                    onClick={() => submitGuess(s.name)}
                    className="block w-full text-left px-3 py-2 text-sm hover:bg-slate-800"
                  >
                    {s.name}
                  </button>
                ))}
              </div>
            )}
          </div>
        )}

        {/* Guess history */}
        <div className="space-y-2">
          {guesses.map((g, i) => {
            const correct = g.name === puzzle.target;
            return (
              <div
                key={i}
                className={`flex items-center justify-between rounded-lg px-3 py-2.5 border ${
                  correct
                    ? "bg-emerald-600/20 border-emerald-600"
                    : "bg-slate-900 border-slate-800"
                }`}
              >
                <span className="font-medium text-sm">{g.name}</span>
                <div className="flex items-center gap-3 text-sm">
                  {correct ? (
                    <span className="text-emerald-400 font-semibold">
                      Correct! 🎯
                    </span>
                  ) : (
                    <>
                      <span className="text-slate-400 tabular-nums">
                        {g.dist.toLocaleString()} km
                      </span>
                      <span
                        className="text-lg"
                        style={{
                          display: "inline-block",
                          transform: `rotate(${g.bng}deg)`,
                        }}
                        title={`${Math.round(g.bng)}°`}
                      >
                        ⬆️
                      </span>
                      <span className="text-emerald-400 tabular-nums w-10 text-right">
                        {g.pct}%
                      </span>
                    </>
                  )}
                </div>
              </div>
            );
          })}
        </div>

        {/* End state */}
        {done && (
          <div className="mt-5 rounded-xl border border-slate-800 bg-slate-900 p-4 text-center">
            <p className="text-lg font-semibold mb-1">
              {won ? "Nice." : "Out of guesses."}
            </p>
            <p className="text-sm text-slate-400 mb-4">
              The missing country was{" "}
              <span className="text-slate-100 font-medium">
                {puzzle.target}
              </span>
              .
            </p>
            <button
              onClick={copyShare}
              className="w-full py-2.5 rounded-lg bg-emerald-600 hover:bg-emerald-500 text-sm font-medium transition"
            >
              {copied ? "Copied!" : "Share result"}
            </button>
            <pre className="mt-3 text-xs text-slate-400 whitespace-pre-wrap text-left bg-slate-950 rounded-lg p-3 border border-slate-800">
              {shareText()}
            </pre>
          </div>
        )}

        {/* Dev controls */}
        <div className="mt-8 pt-4 border-t border-slate-800 flex items-center justify-between text-xs text-slate-500">
          <span>puzzle {puzzleIdx + 1} / {PUZZLES.length}</span>
          <button
            onClick={() =>
              setPuzzleIdx((i) => (i + 1) % PUZZLES.length)
            }
            className="underline underline-offset-2 hover:text-slate-300"
          >
            next puzzle (dev) →
          </button>
        </div>
      </div>
    </div>
  );
}
